name: home-assistant-toolbox
base: core20
version: '0.3' 
summary: "Extend your Home Assistant (home-assistant-snap)"
description: |
  Toolbox contains executables that extends functionality
  to you home-assistant-snap installation.

  The following tools are included:
    - cURL
    - build-essential: make, gcc etc
  + More to come, and feel free to come up with suggestions!

  Requires home-assistant-snap revision 71 or later!
grade: stable
confinement: strict 

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el

slots:
  bin:
    interface: content
    content: executables
    source:
      read:
        - $SNAP/bin
        - $SNAP/etc
        - $SNAP/lib
        - $SNAP/usr

layout:
  /usr/lib:
    bind: $SNAP/usr/lib

parts:
  home-assistant-toolbox:
    plugin: dump
    source: ./src
    source-type: local
  dependencies: # Split this form hat, to prevent pulling it for each change
    plugin: nil
    stage-packages:
      - binutils
      - build-essential
      - curl
      - libc6-dev
      - linux-libc-dev
    override-stage: |
      snapcraftctl stage
      sed -i 's#/usr/lib#/snap/home-assistant-snap/current/shared-bin/usr/lib#g' ${SNAPCRAFT_STAGE}/usr/lib/x86_64-linux-gnu/libc.so
    # organize:
    #   '*': shared-bin
