name: home-assistant-toolbox
base: core20
version: '0.2' 
summary: "Extend your Home Assistant (home-assistant-snap)"
description: |
  Toolbox contains executables that extends functionality
  to you home-assistant-snap installation.

  The following tools are included:
    - cURL
    - make (build-essential)
  + More to come, and feel free to come up with suggestions!

  Requires home-assistant-snap revision 71 or later!
grade: stable
confinement: strict 

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el

slots:
  bin:
    interface: content
    content: executables
    source:
      read:
        - $SNAP/bin
        - $SNAP/etc
        - $SNAP/lib
        - $SNAP/usr

parts:
  home-assistant-toolbox:
    plugin: dump
    source: ./src
    source-type: local
    stage-packages:
      - curl
      - build-essential
